language: ruby
rvm:
- 2.5.1
script:
- bundle exec rails db:migrate
- bundle exec rspec -fd spec
deploy:
  provider: heroku
  api_key:
    secure: T+cYB6cGad09C3BWbNFs8QEJnO8jidOIkBlsrl0Hm3IrPkdrUeKEVLSStEn7efzgVHjhdUJ0dWAnzzR/B6xatfHEQPF8MwxbA70z/ZbyMuiuYsMZXXG7Hp2DWyNFE4yKqDJtvqEzSItwInUlJJqIJe5Oz1W5XCYa98Eieb8uaA7LmtKpWEswyJtffpKFXXUY+oEOWmME+eOQTLKtqA1B8lgnWGLZexwUza7BxHJVNi7/WPYPbCzukm9e3gaktk/gb7Dv3P8qcqphj9SaY2DD+6xj9G9kXzK+KujU1vYxsmdM+4KmFZ9OU5/R+od7q+9lGXibcyXhUxHs9yvld0ftUINqybBngQbocdqhA987FsfPVbobfMa8yu9hgzcROVgHp9xtwdbd7iOGZvU11Kys8GxzXgMIlcEieRp7CrjH8I84QmcTQC0ZGr5jmnDtOJEEuRDpLWsyIpT0SL5sPXrUzhINvZ4+LCtcqfKeo6d4ScfHOhzks88SGTf5/EisK0LHc+CH+ZrqbuYAovQaCKWNu1+7kz6Wu8tX6ZBwnyhTwQBnhpYVKxZcOz5aPkjFUshMelj85bDI8gBZDInhWtACsQJ68CSAlFuAUs8O2VAgcVdlSKWxgaJ1KFi714AHGizG2OxGKZyKFesFqd+bcbEY36QP1BeBvNUovz4AfSyQcYc=
  app: stormy-fortress-25759
  run: "rails db:migrate"
env:
- BEERMAPPING_APIKEY=fdbf6e00d364c11edc03fac44fa40350
- APIXU_APIKEY=fdfd2966f4774635951210319180510
